### ISSUE TITLE
Does it works on RHEL6?

### ISSUE THREAD

**Issue by mimmus** [robertdebock/ansible-role-rsyslog#16]
## Proposed feature

Shame on me but I still have a bunch of servers with RHEL6, currently unmanaged, and I'd like to know if your role works on these. 

## Rationale

Probably it work also on RHEL6 because it has rsyslog-5.8.10

**Comment by robertdebock** [comment]
I'm not sure, I can't test on CentOS 6, but feel free to try and report.
