### ISSUE TITLE
Please add option to turn off "RSYSLOG_TraditionalFileFormat"

### ISSUE THREAD

**Issue by marcin-github** [robertdebock/ansible-role-rsyslog#38]
## Proposed feature

Now RSYSLOG_TraditionalFileFormat is hardcoed into template. I'd like to have option to turn it off.

**Comment by marcin-github** [comment]
I any chance to get it?

**Comment by robertdebock** [comment]
Let me read how this works, thanks for brining it up.

**Comment by marcin-github** [comment]
Thanks!:)
