### ISSUE TITLE
wrong $WorkDirectory in ubuntu

### ISSUE THREAD

**Issue by pescobar** [robertdebock/ansible-role-rsyslog#7]
## Describe the bug

ubuntu18.04 uses `$WorkDirectory /var/spool/rsyslog` but this role deploys `$WorkDirectory /var/lib/rsyslog ` .

folder `/var/spool/rsyslog` doesn't exists at all in ubuntu

## Output

when doing `systemctl status rsyslog` you get this error message:

` $WorkDirectory: /var/lib/rsyslog can not be accessed, probably does not exist - directive ignored`

**Comment by robertdebock** [comment]
Great issue report, thanks!

After applying a fix `image=ubuntu tag=bionic molecule test --destroy=never` shows:

```
root@rsyslog-ubuntu-bionic:/# cat /etc/rsyslog.conf |grep -i work   
$WorkDirectory /var/spool/rsyslog
```

I'll push and release the fixes any moment.
